{
 "title": "Netology Homework 10.3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Availible (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes/node_memory_MemAvailable_bytes*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space on FS (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"}*100",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}